# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orama < Formula
  desc "CLI tool for the Orama decentralized network"
  homepage "https://github.com/DeBrosOfficial/network"
  version "0.102.5-nightly"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/DeBrosOfficial/network/releases/download/v0.102.5-nightly/orama_0.102.5-nightly_darwin_amd64.tar.gz"
      sha256 "edc33248621e62ba1c7ad98553ef5debd3db687bebc6e66f5bda62347cab1c24"

      def install
        bin.install "orama"
      end
    end
    on_arm do
      url "https://github.com/DeBrosOfficial/network/releases/download/v0.102.5-nightly/orama_0.102.5-nightly_darwin_arm64.tar.gz"
      sha256 "1c36c1410088cd5422aaf1a920a0e1bee240f5890d4a14243a6f25103fee83e4"

      def install
        bin.install "orama"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DeBrosOfficial/network/releases/download/v0.102.5-nightly/orama_0.102.5-nightly_linux_amd64.tar.gz"
        sha256 "40fc50a1e9030efd1eb17e1181da70148bdf9bbb4a00a1b7526596472e510687"

        def install
          bin.install "orama"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DeBrosOfficial/network/releases/download/v0.102.5-nightly/orama_0.102.5-nightly_linux_arm64.tar.gz"
        sha256 "a6d81c755b6360634213a15e61b8fdd76bd6f3e9589966cb783b71041a576503"

        def install
          bin.install "orama"
        end
      end
    end
  end

  test do
    system "#{bin}/orama", "--version"
  end
end
