# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orama < Formula
  desc "CLI tool for the Orama decentralized network"
  homepage "https://github.com/DeBrosOfficial/network"
  version "0.102.2-nightly"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/DeBrosOfficial/network/releases/download/v0.102.2-nightly/orama_0.102.2-nightly_darwin_amd64.tar.gz"
      sha256 "efb148e92a6aeb226bcb081301e20b2c4c594039e3d49e976af07f778bb238f3"

      def install
        bin.install "orama"
      end
    end
    on_arm do
      url "https://github.com/DeBrosOfficial/network/releases/download/v0.102.2-nightly/orama_0.102.2-nightly_darwin_arm64.tar.gz"
      sha256 "d118d066ee70946f4da0b5bdf2e5bfe561e1ab54b3496edf6d4f893b0cbbbcac"

      def install
        bin.install "orama"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DeBrosOfficial/network/releases/download/v0.102.2-nightly/orama_0.102.2-nightly_linux_amd64.tar.gz"
        sha256 "8144e1f9646e1942a1eafdde9a1102e229563fe9a83aa4f20530fe7c9bd557b6"

        def install
          bin.install "orama"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DeBrosOfficial/network/releases/download/v0.102.2-nightly/orama_0.102.2-nightly_linux_arm64.tar.gz"
        sha256 "220add1164334348140b28c6c3cf8b8068c3b59bfc4ded8693332a5f5144bcbe"

        def install
          bin.install "orama"
        end
      end
    end
  end

  test do
    system "#{bin}/orama", "--version"
  end
end
