# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orama < Formula
  desc "CLI tool for the Orama decentralized network"
  homepage "https://github.com/DeBrosOfficial/network"
  version "0.102.1-nightly"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/DeBrosOfficial/network/releases/download/v0.102.1-nightly/orama_0.102.1-nightly_darwin_amd64.tar.gz"
      sha256 "f23f338738ff1b192f541f2213cf3d512a7add2b1f82717e34b759290258dca8"

      def install
        bin.install "orama"
      end
    end
    on_arm do
      url "https://github.com/DeBrosOfficial/network/releases/download/v0.102.1-nightly/orama_0.102.1-nightly_darwin_arm64.tar.gz"
      sha256 "fdda8cf316fc78cdfb06a4c3711e4b42047426d0d7f1759d6210b142d6570e35"

      def install
        bin.install "orama"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DeBrosOfficial/network/releases/download/v0.102.1-nightly/orama_0.102.1-nightly_linux_amd64.tar.gz"
        sha256 "c8a633a7da35d7b9b02ef93955d1ca812f6e3fc432df322ac72438381c6d5674"

        def install
          bin.install "orama"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DeBrosOfficial/network/releases/download/v0.102.1-nightly/orama_0.102.1-nightly_linux_arm64.tar.gz"
        sha256 "a2aab25f9d48e7cece03e8db566967d5ca3cd58289b942eedc673c392452ec8d"

        def install
          bin.install "orama"
        end
      end
    end
  end

  test do
    system "#{bin}/orama", "--version"
  end
end
