# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
class Rootwallet < Formula
  desc "RootWallet CLI — terminal wallet for EVM and Solana"
  homepage "https://rootwallet.io"
  version "0.107.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DeBrosDAO/rootwallet/releases/download/v0.107.3/rootwallet_0.107.3_darwin-arm64.tar.gz"
      sha256 "fe1de8f3b227bc80261cf014650ef6e1f5f83a602bd2823dcaba0dbe7369d9f4"
    else
      url "https://github.com/DeBrosDAO/rootwallet/releases/download/v0.107.3/rootwallet_0.107.3_darwin-amd64.tar.gz"
      sha256 "e307ec2fbde9ee57df1437ff66da1740a13212a5850f089b13eab492feeac7bc"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/DeBrosDAO/rootwallet/releases/download/v0.107.3/rootwallet_0.107.3_linux-arm64.tar.gz"
      sha256 "038a2d87243c2e948e0f1eb8732f5ba22d55d75bccc59c378652b83159dabaac"
    else
      url "https://github.com/DeBrosDAO/rootwallet/releases/download/v0.107.3/rootwallet_0.107.3_linux-amd64.tar.gz"
      sha256 "148b60f854ee956a34d0f2749a433588c45dda311488441bd7d7f39d5b88a596"
    end
  end

  def install
    bin.install "rw"
  end

  test do
    system "#{bin}/rw", "--version"
  end
end
