# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
class Rootwallet < Formula
  desc "RootWallet CLI — terminal wallet for EVM and Solana"
  homepage "https://rootwallet.io"
  url "https://registry.npmjs.org/@debros/root-cli/-/root-cli-0.107.5.tgz"
  sha256 "059f0cdefec776bda78a7ff11f8032f49ad969448479c1cf074af75b67595d52"
  version "0.107.5"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rw --version")
  end
end
