# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rules < Formula
  desc "Install DeBros engineering rules and skills into any project for Claude Code"
  homepage "https://github.com/DeBrosDAO/rules"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DeBrosDAO/rules/releases/download/v0.6.0/rules_0.6.0_darwin_amd64.tar.gz"
      sha256 "715dda5c87313f3f398ca23fb6138a556e7186bed4847f3688b8f8efcb6c0111"

      define_method(:install) do
        bin.install "rules"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DeBrosDAO/rules/releases/download/v0.6.0/rules_0.6.0_darwin_arm64.tar.gz"
      sha256 "c0952a5ed9ea053000e7444297c8a199dfc06cb3d530dacd3c885b3511a7b3ab"

      define_method(:install) do
        bin.install "rules"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DeBrosDAO/rules/releases/download/v0.6.0/rules_0.6.0_linux_amd64.tar.gz"
      sha256 "99eb35cdc823bb5c44e5151c8f468ba76fc152666dbac4e59ef0f42afe713401"
      define_method(:install) do
        bin.install "rules"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DeBrosDAO/rules/releases/download/v0.6.0/rules_0.6.0_linux_arm64.tar.gz"
      sha256 "4f0f0fce087d4dc617e0377db0da6b705d34fff3ea36fe190acad4b0144dd22e"
      define_method(:install) do
        bin.install "rules"
      end
    end
  end

  test do
    system "#{bin}/rules", "version"
  end
end
